@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

top to bottom direction
skinparam nodesep 90
skinparam ranksep 70

database "Social" as SN <<source>>
database "E-commerce" as EC <<source>>
database "IoT" as IO <<source>>
database "Telecom" as TC <<source>>

cloud "Big Data\nPlatform" as BD <<store>>

SN -down-> BD
EC -down-> BD
IO -down-> BD
TC -down-> BD

@enduml
