@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

top to bottom direction
skinparam nodesep 100
skinparam ranksep 70

cloud "Data\nGenerated Daily" as D <<store>>
rectangle "Scientists" as S <<good>>
rectangle "Engineers" as E <<process>>

D -down-> S
D -down-> E

@enduml
