@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

left to right direction
skinparam nodesep 100
skinparam ranksep 70

rectangle "ML\nDeployment" as ML <<process>>
rectangle "Data &\nMetadata" as DB <<store>>
rectangle "Monitoring" as M <<good>>

ML -right-> DB
DB -right-> M

@enduml
