@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

left to right direction
skinparam nodesep 100
skinparam ranksep 70

rectangle "Data\nEngineering" as DE <<process>>
rectangle "Shared" as O <<store>>
rectangle "Data\nScience" as DS <<good>>

DE -right-> O : Provides
O -right-> DS : Enables
DS -[dashed]left-> DE : Feedback

@enduml
