@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

top to bottom direction
skinparam nodesep 80
skinparam ranksep 60

rectangle "Social" as So <<source>>
rectangle "E-commerce" as Ec <<source>>
rectangle "Weather" as W <<source>>
rectangle "Telecom" as T <<source>>
rectangle "Markets" as M <<source>>

component "Extract\nIngest" as E <<process>>
cloud "Central\nPlatform" as BD <<store>>

So -down-> E
Ec -down-> E
W -down-> E
T -down-> E
M -down-> E
E -down-> BD

@enduml
