@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

top to bottom direction
skinparam nodesep 100
skinparam ranksep 70

rectangle "Batch" as B <<process>>
rectangle "Stream" as S <<process>>
rectangle "Hybrid" as H <<good>>

B -down-> H : History
S -down-> H : Real-time

@enduml
