@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

left to right direction
skinparam nodesep 120
skinparam ranksep 70

storage "Sources" as S <<source>>
component "ETL" as P <<process>>
database "Output" as O <<store>>

S -right-> P : Raw
P -right-> O : Clean

@enduml
