@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

top to bottom direction
skinparam nodesep 100
skinparam ranksep 70

cloud "Data Platform" as P <<store>>

database "Databases" as DB <<store>>
database "Warehouses" as WH <<store>>
rectangle "Integration\nTools" as I <<process>>
rectangle "Analytical\nSystems" as A <<good>>

P -down-> DB
P -down-> WH
P -down-> I
P -down-> A

@enduml
