@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

left to right direction
skinparam nodesep 100
skinparam ranksep 70

rectangle "Velocity" as V1 <<source>>
rectangle "Variety" as V2 <<process>>
rectangle "Volume" as V3 <<store>>

V1 -right-> V2
V2 -right-> V3

@enduml
