@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

top to bottom direction
skinparam nodesep 80
skinparam ranksep 60

rectangle "Volume Scale" as H <<process>>

rectangle "GB" as GB <<source>>
rectangle "TB\n(1024 GB)" as TB <<store>>
rectangle "PB\n(1024 TB)" as PB <<store>>

H -down-> GB
GB -down-> TB
TB -down-> PB

@enduml
