@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

top to bottom direction
skinparam nodesep 80
skinparam ranksep 60

rectangle "Data" as D <<source>>
rectangle "Information" as I <<process>>
rectangle "Knowledge" as K <<process>>
rectangle "Wisdom" as W <<good>>

D -up-> I : Process
I -up-> K : Analyze
K -up-> W : Apply

@enduml
