@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

left to right direction
skinparam nodesep 120
skinparam ranksep 70

storage "Input" as I <<source>>
component "Transform" as T <<process>>
database "Output" as O <<store>>

I -right-> T : Ingest
T -right-> O : Write

@enduml
