@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

top to bottom direction
skinparam nodesep 100
skinparam ranksep 70

cloud "Big Data\nEcosystem" as BD <<store>>

rectangle "Storage" as S <<source>>
rectangle "Processing" as P <<process>>
rectangle "Orchestration" as O <<process>>

BD -down-> S
BD -down-> P
BD -down-> O

@enduml
