@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

top to bottom direction
skinparam nodesep 100
skinparam ranksep 70

database "Data" as D <<store>>
rectangle "Data\nScientist" as DS <<good>>
rectangle "Data\nEngineer" as DE <<process>>

D -down-> DS
D -down-> DE

@enduml
