@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

left to right direction
skinparam nodesep 100
skinparam ranksep 70

rectangle "Batch" as B <<process>>
rectangle "Streaming" as S <<process>>

rectangle "Scheduled\nLarge window" as B1 <<store>>
rectangle "Continuous\nEvent-by-event" as S1 <<source>>
rectangle "Latency:\nmin–hours" as B2 <<decision>>
rectangle "Latency:\nseconds" as S2 <<good>>

B -down-> B1
B1 -down-> B2
S -down-> S1
S1 -down-> S2

@enduml
