@startuml
!include ../_template_styles.puml
!include _week1_visual_style.puml

top to bottom direction
skinparam nodesep 90
skinparam ranksep 70

rectangle "Scale" as S <<risk>>
rectangle "Variety" as V <<risk>>
rectangle "Velocity" as Ve <<risk>>
rectangle "Reliability" as R <<good>>

S -down-> V
V -right-> Ve
Ve -down-> R

@enduml
