@startuml
!include ../_template_styles.puml
!include _week5_visual_style.puml

left to right direction
skinparam nodesep 70
skinparam ranksep 60

database "year" as Y <<store>>
database "quarter" as Q <<store>>
database "month" as M <<store>>
database "day" as D <<store>>

database "category" as C <<store>>
database "brand" as B <<store>>
database "line" as L <<store>>
database "product" as P <<store>>

Y -right-> Q
Q -right-> M
M -right-> D

C -right-> B
B -right-> L
L -right-> P

Y -[hidden]down- C
D -[hidden]right- P

@enduml
