@startuml
!include ../_template_styles.puml
!include _week5_visual_style.puml

left to right direction
skinparam nodesep 70
skinparam ranksep 60

rectangle "Star" as STAR {
  database "sales_fact" as F1 <<store>>
  database "dim_customer" as DC <<store>>
  database "dim_product" as DP <<store>>
  database "dim_date" as DD <<store>>
  F1 -up-> DC
  F1 -up-> DP
  F1 -up-> DD
  DC -[hidden]right- DP
  DP -[hidden]right- DD
}

rectangle "Snowflake" as SNOW {
  database "sales_fact" as F2 <<store>>
  database "dim_product" as D2P <<store>>
  database "dim_brand" as DB <<store>>
  database "dim_category" as D2C <<store>>
  F2 -up-> D2P
  D2P -up-> DB
  DB -up-> D2C
}

F1 -[hidden]right- F2

@enduml
