@startuml
!include ../_template_styles.puml
!include _week5_visual_style.puml

top to bottom direction
skinparam nodesep 80
skinparam ranksep 60

database "dim_customer" as DIM_C <<store>>
database "dim_product" as DIM_P <<store>>
database "dim_date" as DIM_D <<store>>
database "sales_fact" as FACT <<store>>

DIM_C -down-> FACT
DIM_P -down-> FACT
DIM_D -down-> FACT

@enduml
