@startuml
!include ../_template_styles.puml
!include _week5_visual_style.puml

top to bottom direction
skinparam nodesep 70
skinparam ranksep 55

rectangle "v1 Single table" as V1 {
  database "One big table" as T1 <<risk>>
  component "BI" as BI1 <<process>>
  BI1 -down-> T1
}

rectangle "v2 Star" as V2 {
  database "sales_fact" as F2 <<store>>
  database "dims" as D2 <<store>>
  component "BI" as BI2 <<good>>
  BI2 -down-> F2
  F2 -down-> D2
  BI2 -down-> D2
}

T1 -[hidden]right- F2

@enduml
