@startuml
!include ../_template_styles.puml
!include _week5_visual_style.puml

top to bottom direction
skinparam nodesep 75
skinparam ranksep 58

rectangle "Sources" as SRC {
  database "DB / API" as SRC1 <<source>>
  database "Files / Logs" as SRC2 <<source>>
}

component "ETL / ELT" as ETL <<process>>

rectangle "Storage" as STO {
  database "DWH" as DWH <<store>>
  database "Lake" as LAKE <<store>>
}

component "BI / Analytics" as BI <<good>>

SRC1 -down-> ETL
SRC2 -down-> ETL
ETL -down-> DWH
ETL -down-> LAKE
DWH -down-> BI
LAKE -down-> BI

@enduml
