@startuml
!include ../_template_styles.puml
!include _week5_visual_style.puml

top to bottom direction
skinparam nodesep 90
skinparam ranksep 65

rectangle "Subject-Oriented" as SUBJ <<process>>
rectangle "Integrated" as INT <<process>>
rectangle "Time-Variant" as TIME <<process>>
rectangle "Non-Volatile" as NONV <<process>>
database "Data Warehouse" as DWH <<good>>

SUBJ -down-> DWH
INT -down-> DWH
TIME -down-> DWH
NONV -down-> DWH

@enduml
