@startuml
!include ../_template_styles.puml
!include _week5_visual_style.puml

top to bottom direction
skinparam nodesep 70
skinparam ranksep 55

rectangle "Query" as QRY {
  component "SQL" as SQL <<process>>
}

rectangle "Planner" as PLN {
  component "Partition pruning" as PRUNE <<process>>
}

rectangle "Scan" as SCN {
  component "Scan fact" as SCAN1 <<process>>
}

rectangle "Join / Agg" as JN {
  component "Join · Aggregate" as JOIN <<process>>
}

database "Result" as RESULT <<good>>

SQL -down-> PRUNE
PRUNE -down-> SCAN1
SCAN1 -down-> JOIN
JOIN -down-> RESULT

@enduml
