@startuml
!include ../_template_styles.puml
!include _week4_visual_style.puml

start
:Read source schema;
:Map to target;
if (Type mismatch?) then (yes)
  :Apply conversion;
else (no)
  :Pass-through;
endif
if (Unknown?) then (yes)
  :Surrogate key;
endif
:Write STTM spec;
stop

@enduml
