@startuml
!include ../_template_styles.puml
!include _week4_visual_style.puml

left to right direction
skinparam nodesep 90
skinparam ranksep 70

database "Staging" as STG <<store>>
component "Validate" as VALID <<process>>
database "Target" as TGT <<good>>
database "DLQ" as DLQ <<failure>>

STG -right-> VALID
VALID -right-> TGT : valid
VALID -down-> DLQ : invalid

@enduml
