@startuml
!include ../_template_styles.puml
!include _week4_visual_style.puml

left to right direction
skinparam nodesep 80
skinparam ranksep 65

database "Source" as SRC <<source>>
database "Control" as CTRL <<store>>
component "Extract" as EXTRACT <<process>>
database "Target" as TGT <<good>>

CTRL -down-> EXTRACT : watermark
SRC -right-> EXTRACT : slice
EXTRACT -right-> TGT : MERGE
TGT -up-> CTRL : update

@enduml
