@startuml
!include ../_template_styles.puml
!include _week4_visual_style.puml

left to right direction
skinparam nodesep 75
skinparam ranksep 65

rectangle "Snapshot" as S <<process>>
rectangle "Timestamp" as T <<process>>
rectangle "Log-based" as L <<good>>
rectangle "Trigger" as G <<process>>

S -right-> T
T -right-> L
L -right-> G

@enduml
