@startuml
!include ../_template_styles.puml
!include _week4_visual_style.puml

top to bottom direction
skinparam nodesep 100
skinparam ranksep 70

rectangle "MERGE" as MERGE <<process>>
rectangle "Partition\nOverwrite" as OVER <<process>>
rectangle "Choose" as CHOICE <<decision>>

MERGE -down-> CHOICE
OVER -down-> CHOICE

@enduml
