@startuml
!include ../_template_styles.puml
!include _week4_visual_style.puml

left to right direction
skinparam nodesep 90
skinparam ranksep 70

database "Source" as SRC <<source>>
rectangle "ETL" as ETL <<process>>
rectangle "ELT" as ELT <<process>>
database "Target" as TGT <<good>>

SRC -right-> ETL : Extract
SRC -right-> ELT : Extract
ETL -right-> TGT : Load clean
ELT -right-> TGT : Load raw

@enduml
