@startuml
!include ../_template_styles.puml
!include _week4_visual_style.puml

top to bottom direction
skinparam nodesep 70
skinparam ranksep 55

rectangle "Run 1" as R1 {
  component "P1" as P1 <<good>>
  component "P2" as P2 <<good>>
  component "P3" as P3 <<failure>>
  P1 -[hidden]right- P2
  P2 -[hidden]right- P3
}

database "Target" as TARGET <<store>>

rectangle "Run 2" as R2 {
  component "Skip P1,P2" as SKIP <<process>>
  component "Process P3" as P3B <<process>>
  SKIP -right-> P3B
}

P1 -down-> TARGET
P2 -down-> TARGET
P3 -down-> TARGET : fails
P3B -down-> TARGET

@enduml
