@startuml
!include ../_template_styles.puml
' FAILURE: DATA SKEW (HOT KEY -> ONE REDUCER) - Mixed layout for PPTX
top to bottom direction

component "**Partition by hash(key)**\n<size:10>Keys -> Reducers</size>" as PART <<Control>>

rectangle "REDUCERS" #FFFFFF {
    component "**R1**\n<size:10>10 keys, 1M vals</size>" as R1 <<Task>>
    component "**R2**\n<size:10>10 keys, 1M vals</size>" as R2 <<Task>>
    component "**R3 (HOT)**\n<size:10>1 key, 800M vals</size>" as R3 <<Failure>>
    R1 -[hidden]right- R2
    R2 -[hidden]right- R3
}

together {
    database "**Done**" as D1 <<up>>
    database "**Done**" as D2 <<up>>
    component "**OOM / Timeout**\n<size:10>Overloaded</size>" as FAIL <<failure>>
}

component "**Mitigation**\n<size:10>salting / combiner</size>" as FIX <<Control>>

PART -down-> R1 : balanced
PART -down-> R2 : balanced
PART -down-> R3 : hot key

R1 -down-> D1
R2 -down-> D2
R3 -down-> FAIL : crash
FAIL -down-> FIX : rebalance

@enduml
