@startuml
!include ../_template_styles.puml
!include _week2_visual_style.puml

left to right direction
skinparam nodesep 75
skinparam ranksep 70

rectangle "P1" as P1 <<source>>
rectangle "P2" as P2 <<process>>
rectangle "P3" as P3 <<decision>>

rectangle "Node A\nP1* P2r P3r" as NA <<good>>
rectangle "Node B\nP2* P3r P1r" as NB <<good>>
rectangle "Node C\nP3* P1r P2r" as NC <<good>>

rectangle "r = 3" as RF <<store>>

P1 -right-> NA
P2 -right-> NB
P3 -right-> NC

NA -[dashed]-> NB : repl
NB -[dashed]-> NC : repl
NC -[dashed]-> NA : repl

NA -down-> RF
NB -down-> RF
NC -down-> RF

@enduml
