@startuml
!include ../_template_styles.puml

left to right direction
skinparam nodesep 120
skinparam ranksep 90

component "2PC Coordinator" as C

database "Participant A\nPrepared" as A
database "Participant B\nPrepared" as B
database "Participant C\nPrepared" as D

C -right-> A : PREPARE?
C -right-> B : PREPARE?
C -right-> D : PREPARE?

A -left-> C : YES
B -left-> C : YES
D -left-> C : YES

cloud "Coordinator crash\nbefore COMMIT" as X <<Failure>>
X -down-> C

component "Locks held\ntransaction blocked" as BLK <<Failure>>
A -down-> BLK
B -down-> BLK
D -down-> BLK

@enduml
