@startuml
!include ../_template_styles.puml
!include _week2_visual_style.puml

top to bottom direction
skinparam nodesep 65
skinparam ranksep 60

rectangle "Data Model Choice" as ROOT <<store>>

rectangle "SQL" as SQL <<process>>
rectangle "NoSQL" as NOS <<decision>>

rectangle "ACID" as SQ1 <<good>>
rectangle "JOINs" as SQ2 <<good>>
rectangle "Schema" as SQ3 <<good>>

rectangle "Key Lookup" as NQ1 <<risk>>
rectangle "Scale Out" as NQ2 <<risk>>
rectangle "Flexible" as NQ3 <<risk>>

ROOT -down-> SQL
ROOT -down-> NOS

SQL -down-> SQ1
SQL -down-> SQ2
SQL -down-> SQ3

NOS -down-> NQ1
NOS -down-> NQ2
NOS -down-> NQ3

@enduml
